# jazzy --config .jazzy.yml
author: "Big Nerd Ranch"
author_url: "http://bignerdranch.github.io"
copyright: "© 2014-2016 [Big Nerd Ranch](//www.bignerdranch.com) under [MIT license](//github.com/bignerdranch/Deferred/blob/master/LICENSE.txt)."
custom_categories:
  - name: Futures and Promises
    children:
    - Deferred
    - FutureType
    - PromiseType
    - Timeout
  - name: Transforming Future
    children:
    - Future
    - CollectionType
    - SequenceType
    - IgnoringFuture
  - name: Controlling Where Callbacks Execute
    children:
    - ExecutorType
    - NSOperationQueue
    - NSRunLoop
    - CFRunLoop
  - name: Coordinating Access to Data
    children:
    - LockProtected
    - ReadWriteLock
  - name: Coordination Primitives
    children:
    - DispatchLock
    - SpinLock
    - CASSpinLock
    - PThreadReadWriteLock
github_url: "https://github.com/bignerdranch/Deferred"
head: |
  <meta property="og:site_name" content="Deferred Programming Guide">
  <meta property="og:description" content="An implementation of OCaml's Deferred for Swift. It lets you work with values that haven't been determined yet, like an array that's coming later from a web service call.">
  <meta property="og:image" content="//www.bignerdranch.com/img/bnr-logo-square.png">
  <link rel="shortcut icon" type="image/x-icon" href="//www.bignerdranch.com/favicon.png">
hide_documentation_coverage: true
module: Deferred
module_version: "3.0.0-beta.1"
root_url: "http://bignerdranch.github.io/Deferred/"
theme: fullwidth
